### PR TITLE
Apply (auto-icebreaker) to pumpable breakers

### PR DESCRIPTION
**Pull request by JoelCFC25**
As discussed in [#336](https://github.com/mtgred/netrunner/issues/336)...

### CODE REVIEW

**Comment by nealterrell** [comment]
Super cool.

Do you want to take a crack at incorporating the logic of AI icebreakers into `breaker-auto-pump`? The line 

``` clojure
(and (:rezzed current-ice) (some #(has? current-ice :subtype %) (:breaks card))
                                    (> strdif 0))
```

checks to see if the encountered ice is rezzed, if it has a subtype that the icebreaker can break, and has a strength at least 1 higher than the breaker. We would need the subtype logic to turn into "if the ice has a subtype that the icebreaker can break, OR if the icebreaker's `:breaks` contains "All"". Give it a shot :).

[I am a teacher, annoyingly suggesting that you try new challenges is part of the job :P]

**Comment by JoelCFC25** [comment]
I dig it :+1:  I _think_ that challenge was fairly straightforward...

**Comment by nealterrell** [comment]
Minor technicality - :breaks is a vector that will contain "All" and not
literally the string "All". The proper test should be if the first thing in
:breaks is equal to "All".

**Comment by nealterrell** [comment]
:+1:

**Pull request merged**
